name: MonsterIndustries
main: me.lewismercer.monsterIndustries.MonsterIndustries
author: lewismercer
version: 1.0
description: Monster Industries mini-game
api-version: 1.15
commands:
  mi:
    description:  Main command!